/**
 * Static climate data for all supported destinations
 * Used when travel date is more than 7 days away
 * Data based on average historical weather patterns
 */

export interface ClimateData {
  temp: string; // e.g. "15-22°C"
  condition: string; // e.g. "Sunny"
  icon?: string; // Emoji icon for the condition
  description?: string; // Detailed explanation
}

export const climateDatabase: Record<string, Record<string, ClimateData>> = {
  "United States": {
    January: { temp: "2-10°C", condition: "Cold & Clear", icon: "❄️", description: "Winter weather with occasional snow" },
    February: { temp: "3-12°C", condition: "Cold", icon: "❄️", description: "Still cold, some areas may have snow" },
    March: { temp: "7-16°C", condition: "Mild", icon: "🌤️", description: "Spring arriving, variable conditions" },
    April: { temp: "12-21°C", condition: "Pleasant", icon: "🌼", description: "Mild and mostly dry" },
    May: { temp: "17-26°C", condition: "Warm", icon: "☀️", description: "Beautiful weather for outdoor activities" },
    June: { temp: "22-30°C", condition: "Warm & Sunny", icon: "☀️", description: "Summer begins, perfect travel weather" },
    July: { temp: "24-32°C", condition: "Hot & Humid", icon: "🔥", description: "Peak summer heat, thunderstorms possible" },
    August: { temp: "23-31°C", condition: "Hot", icon: "🌡️", description: "Still very warm, hurricane season risk" },
    September: { temp: "19-27°C", condition: "Warm", icon: "🌤️", description: "Late summer, cooling down gradually" },
    October: { temp: "13-21°C", condition: "Pleasant", icon: "🍂", description: "Fall colors, comfortable temperatures" },
    November: { temp: "7-15°C", condition: "Cool", icon: "☁️", description: "Getting colder, occasional rain" },
    December: { temp: "2-10°C", condition: "Cold", icon: "❄️", description: "Winter weather, possible snow" },
  },
  France: {
    January: { temp: "2-8°C", condition: "Cold", icon: "❄️", description: "Winter in France, cool but manageable" },
    February: { temp: "2-9°C", condition: "Cold", icon: "❄️", description: "Still chilly, similar to January" },
    March: { temp: "5-13°C", condition: "Cool", icon: "🌤️", description: "Spring starting, variable weather" },
    April: { temp: "9-17°C", condition: "Pleasant", icon: "🌼", description: "Spring flowers blooming, mild weather" },
    May: { temp: "13-21°C", condition: "Warm", icon: "☀️", description: "Beautiful weather for sightseeing" },
    June: { temp: "17-25°C", condition: "Sunny", icon: "☀️", description: "Early summer, perfect for travel" },
    July: { temp: "20-28°C", condition: "Sunny", icon: "🔥", description: "Peak summer season, very warm" },
    August: { temp: "19-27°C", condition: "Warm", icon: "🌡️", description: "Still hot, many French people on vacation" },
    September: { temp: "15-22°C", condition: "Pleasant", icon: "🍂", description: "Fall arrives, still warm and pleasant" },
    October: { temp: "10-16°C", condition: "Cool", icon: "☁️", description: "Fall colors, cooler temperatures" },
    November: { temp: "6-11°C", condition: "Cold", icon: "🌧️", description: "Getting colder, more rain" },
    December: { temp: "3-8°C", condition: "Cold", icon: "❄️", description: "Winter, occasional frost" },
  },
  Japan: {
    January: { temp: "3-10°C", condition: "Cold & Dry", icon: "❄️", description: "Winter season, clear skies" },
    February: { temp: "3-11°C", condition: "Cold", icon: "❄️", description: "Still cold but starting to warm" },
    March: { temp: "7-17°C", condition: "Cool", icon: "🌸", description: "Cherry blossom season approaching" },
    April: { temp: "13-23°C", condition: "Mild & Sunny", icon: "🌸", description: "Cherry blossoms in full bloom" },
    May: { temp: "18-27°C", condition: "Warm", icon: "☀️", description: "Golden week holidays, pleasant weather" },
    June: { temp: "21-28°C", condition: "Hot & Humid", icon: "💦", description: "Rainy season (tsuyu) begins" },
    July: { temp: "25-32°C", condition: "Very Hot & Humid", icon: "🔥", description: "Peak summer heat and humidity" },
    August: { temp: "26-33°C", condition: "Hot & Humid", icon: "🌡️", description: "Still very hot, typhoon season risk" },
    September: { temp: "20-27°C", condition: "Warm & Humid", icon: "⛈️", description: "Typhoon season, cooling down" },
    October: { temp: "14-22°C", condition: "Pleasant", icon: "🍁", description: "Fall foliage, comfortable weather" },
    November: { temp: "9-17°C", condition: "Cool", icon: "🍂", description: "Autumn colors peak, getting chilly" },
    December: { temp: "4-11°C", condition: "Cold", icon: "❄️", description: "Winter approaches, clear days" },
  },
  Thailand: {
    January: { temp: "24-32°C", condition: "Sunny & Dry", icon: "☀️", description: "Best weather for travel" },
    February: { temp: "25-33°C", condition: "Sunny & Hot", icon: "☀️", description: "Perfect beach weather" },
    March: { temp: "27-35°C", condition: "Very Hot", icon: "🔥", description: "Peak summer heat begins" },
    April: { temp: "28-36°C", condition: "Hot & Humid", icon: "🌡️", description: "Hottest month, Songkran festival" },
    May: { temp: "25-33°C", condition: "Hot & Rainy", icon: "🌧️", description: "Rainy season starts" },
    June: { temp: "24-31°C", condition: "Rainy", icon: "💦", description: "Southwest monsoon, frequent rain" },
    July: { temp: "24-30°C", condition: "Rainy & Hot", icon: "⛈️", description: "Heavy rain, high humidity" },
    August: { temp: "23-30°C", condition: "Rainy", icon: "🌧️", description: "Rainy season continues" },
    September: { temp: "23-30°C", condition: "Rainy", icon: "⛈️", description: "Heaviest rain month" },
    October: { temp: "23-31°C", condition: "Rainy & Warm", icon: "🌧️", description: "Rain decreasing towards end" },
    November: { temp: "22-31°C", condition: "Dry & Sunny", icon: "☀️", description: "Start of cool season" },
    December: { temp: "21-30°C", condition: "Sunny & Dry", icon: "🌞", description: "Best season, comfortable heat" },
  },
  Spain: {
    January: { temp: "5-14°C", condition: "Cool", icon: "☁️", description: "Winter, occasional rain" },
    February: { temp: "6-15°C", condition: "Cool", icon: "☁️", description: "Still cold but improving" },
    March: { temp: "8-18°C", condition: "Mild", icon: "🌤️", description: "Spring beginning" },
    April: { temp: "11-21°C", condition: "Pleasant", icon: "🌼", description: "Nice spring weather" },
    May: { temp: "15-26°C", condition: "Warm", icon: "☀️", description: "Perfect for outdoor activities" },
    June: { temp: "20-31°C", condition: "Hot & Sunny", icon: "☀️", description: "Summer season, very warm" },
    July: { temp: "23-34°C", condition: "Very Hot & Sunny", icon: "🔥", description: "Peak heat, peak season" },
    August: { temp: "22-33°C", condition: "Hot", icon: "🌡️", description: "Still very hot, many on vacation" },
    September: { temp: "18-29°C", condition: "Warm", icon: "🌤️", description: "Cooling down, still pleasant" },
    October: { temp: "13-22°C", condition: "Pleasant", icon: "🍂", description: "Fall weather, comfortable" },
    November: { temp: "8-16°C", condition: "Cool", icon: "☁️", description: "Getting colder, some rain" },
    December: { temp: "5-12°C", condition: "Cold", icon: "❄️", description: "Winter arrives" },
  },
  Italy: {
    January: { temp: "3-12°C", condition: "Cold", icon: "❄️", description: "Winter season" },
    February: { temp: "4-13°C", condition: "Cold", icon: "❄️", description: "Still cold but improving" },
    March: { temp: "7-17°C", condition: "Cool", icon: "🌤️", description: "Spring approaching" },
    April: { temp: "12-22°C", condition: "Pleasant", icon: "🌼", description: "Perfect spring weather" },
    May: { temp: "17-27°C", condition: "Warm & Sunny", icon: "☀️", description: "Beautiful weather for travel" },
    June: { temp: "21-31°C", condition: "Hot & Sunny", icon: "☀️", description: "Summer begins" },
    July: { temp: "24-33°C", condition: "Very Hot", icon: "🔥", description: "Peak summer heat" },
    August: { temp: "23-32°C", condition: "Hot", icon: "🌡️", description: "Still very warm" },
    September: { temp: "19-28°C", condition: "Warm", icon: "🌤️", description: "Late summer, cooling slightly" },
    October: { temp: "13-22°C", condition: "Pleasant", icon: "🍂", description: "Fall weather, comfortable" },
    November: { temp: "8-16°C", condition: "Cool", icon: "☁️", description: "Getting cooler" },
    December: { temp: "4-12°C", condition: "Cold", icon: "❄️", description: "Winter weather" },
  },
  Australia: {
    January: { temp: "25-35°C", condition: "Hot & Humid", icon: "🔥", description: "Peak summer heat" },
    February: { temp: "24-34°C", condition: "Hot", icon: "🌡️", description: "Still very hot" },
    March: { temp: "21-31°C", condition: "Warm", icon: "🌤️", description: "Autumn beginning" },
    April: { temp: "17-27°C", condition: "Pleasant", icon: "🍂", description: "Cool autumn weather" },
    May: { temp: "13-22°C", condition: "Cool", icon: "☁️", description: "Autumn in full swing" },
    June: { temp: "10-18°C", condition: "Cold", icon: "❄️", description: "Winter beginning" },
    July: { temp: "9-17°C", condition: "Cold", icon: "❄️", description: "Coldest month" },
    August: { temp: "11-19°C", condition: "Cool", icon: "☀️", description: "Starting to warm up" },
    September: { temp: "14-24°C", condition: "Pleasant", icon: "🌸", description: "Spring beginning" },
    October: { temp: "19-29°C", condition: "Warm & Sunny", icon: "☀️", description: "Spring in full swing" },
    November: { temp: "22-32°C", condition: "Warm", icon: "🔥", description: "Summer approaching" },
    December: { temp: "24-34°C", condition: "Hot", icon: "🌡️", description: "Summer begins" },
  },
  Greece: {
    January: { temp: "6-13°C", condition: "Cool", icon: "☁️", description: "Winter on the islands" },
    February: { temp: "7-14°C", condition: "Cool", icon: "☁️", description: "Still chilly" },
    March: { temp: "9-17°C", condition: "Mild", icon: "🌤️", description: "Spring approaching" },
    April: { temp: "15-24°C", condition: "Pleasant", icon: "🌼", description: "Easter weather improving" },
    May: { temp: "20-29°C", condition: "Warm & Sunny", icon: "☀️", description: "Perfect beach weather" },
    June: { temp: "25-33°C", condition: "Hot & Sunny", icon: "☀️", description: "Summer season" },
    July: { temp: "28-35°C", condition: "Very Hot & Sunny", icon: "🔥", description: "Peak summer" },
    August: { temp: "27-35°C", condition: "Hot", icon: "🌡️", description: "Very hot, peak tourism" },
    September: { temp: "23-31°C", condition: "Warm", icon: "🌤️", description: "Late summer" },
    October: { temp: "17-26°C", condition: "Pleasant", icon: "🍂", description: "Fall weather" },
    November: { temp: "11-20°C", condition: "Cool", icon: "☁️", description: "Getting cooler" },
    December: { temp: "7-14°C", condition: "Cool", icon: "❄️", description: "Winter season" },
  },
  Brazil: {
    January: { temp: "25-34°C", condition: "Hot & Humid", icon: "💦", description: "Summer season" },
    February: { temp: "25-34°C", condition: "Hot & Humid", icon: "🔥", description: "Carnival season" },
    March: { temp: "24-32°C", condition: "Warm & Humid", icon: "💦", description: "Cooling slightly" },
    April: { temp: "22-30°C", condition: "Warm", icon: "🌤️", description: "Fall beginning" },
    May: { temp: "19-27°C", condition: "Pleasant", icon: "☀️", description: "Comfortable temperatures" },
    June: { temp: "17-25°C", condition: "Cool", icon: "☁️", description: "Winter beginning" },
    July: { temp: "16-24°C", condition: "Cool", icon: "❄️", description: "Coldest month" },
    August: { temp: "17-26°C", condition: "Cool & Dry", icon: "☀️", description: "Dry season" },
    September: { temp: "20-28°C", condition: "Warm & Dry", icon: "🌼", description: "Spring beginning" },
    October: { temp: "23-31°C", condition: "Warm", icon: "☀️", description: "Heating up" },
    November: { temp: "24-32°C", condition: "Hot & Humid", icon: "💦", description: "Summer approaching" },
    December: { temp: "25-33°C", condition: "Hot & Humid", icon: "🔥", description: "Summer begins" },
  },
  Canada: {
    January: { temp: "-10 to -2°C", condition: "Very Cold", icon: "❄️", description: "Deep winter, snow common" },
    February: { temp: "-10 to -1°C", condition: "Very Cold", icon: "❄️", description: "Still very cold" },
    March: { temp: "-5 to 4°C", condition: "Cold", icon: "❄️", description: "Spring snow still possible" },
    April: { temp: "2 to 12°C", condition: "Cool", icon: "🌤️", description: "Spring thaw beginning" },
    May: { temp: "10 to 20°C", condition: "Pleasant", icon: "🌼", description: "Spring in full swing" },
    June: { temp: "16 to 25°C", condition: "Warm", icon: "☀️", description: "Beautiful early summer" },
    July: { temp: "19 to 27°C", condition: "Warm & Sunny", icon: "☀️", description: "Peak summer" },
    August: { temp: "18 to 26°C", condition: "Warm", icon: "🌤️", description: "Still pleasant" },
    September: { temp: "13 to 20°C", condition: "Cool", icon: "🍂", description: "Fall colors starting" },
    October: { temp: "7 to 14°C", condition: "Cool", icon: "🍁", description: "Fall in full swing" },
    November: { temp: "1 to 7°C", condition: "Cold", icon: "☁️", description: "Getting ready for winter" },
    December: { temp: "-7 to -1°C", condition: "Very Cold", icon: "❄️", description: "Winter returns" },
  },
  Mexico: {
    January: { temp: "20-27°C", condition: "Warm & Dry", icon: "☀️", description: "Dry season begins" },
    February: { temp: "21-28°C", condition: "Warm & Dry", icon: "☀️", description: "Perfect beach weather" },
    March: { temp: "23-30°C", condition: "Hot & Dry", icon: "🔥", description: "Getting warmer" },
    April: { temp: "25-32°C", condition: "Hot", icon: "🌡️", description: "Very warm, before rains" },
    May: { temp: "25-33°C", condition: "Hot & Humid", icon: "💦", description: "Rainy season approaching" },
    June: { temp: "24-31°C", condition: "Hot & Rainy", icon: "🌧️", description: "Rainy season begins" },
    July: { temp: "23-30°C", condition: "Warm & Rainy", icon: "⛈️", description: "Heavy rain possible" },
    August: { temp: "23-30°C", condition: "Warm & Rainy", icon: "🌧️", description: "Rainy season continues" },
    September: { temp: "23-29°C", condition: "Warm & Rainy", icon: "⛈️", description: "Hurricane season" },
    October: { temp: "22-30°C", condition: "Warm & Rainy", icon: "🌧️", description: "Rains decreasing" },
    November: { temp: "20-28°C", condition: "Warm & Dry", icon: "☀️", description: "Dry season returning" },
    December: { temp: "19-26°C", condition: "Warm & Dry", icon: "☀️", description: "Perfect weather" },
  },
}

const _climateDatabase2: Record<string, Record<string, ClimateData>> = {
  "United States": {
    January: { temp: "2-10°C", condition: "Cold & Clear", description: "Winter weather with occasional snow" },
    February: { temp: "3-12°C", condition: "Cold", description: "Still cold, some areas may have snow" },
    March: { temp: "7-16°C", condition: "Mild", description: "Spring arriving, variable conditions" },
    April: { temp: "12-21°C", condition: "Pleasant", description: "Mild and mostly dry" },
    May: { temp: "17-26°C", condition: "Warm", description: "Beautiful weather for outdoor activities" },
    June: { temp: "22-30°C", condition: "Warm & Sunny", description: "Summer begins, perfect travel weather" },
    July: { temp: "24-32°C", condition: "Hot & Humid", description: "Peak summer heat, thunderstorms possible" },
    August: { temp: "23-31°C", condition: "Hot", description: "Still very warm, hurricane season risk" },
    September: { temp: "19-27°C", condition: "Warm", description: "Late summer, cooling down gradually" },
    October: { temp: "13-21°C", condition: "Pleasant", description: "Fall colors, comfortable temperatures" },
    November: { temp: "7-15°C", condition: "Cool", description: "Getting colder, occasional rain" },
    December: { temp: "2-10°C", condition: "Cold", description: "Winter weather, possible snow" },
  },
  "France": {
    January: { temp: "2-8°C", condition: "Cold", description: "Winter in France, cool but manageable" },
    February: { temp: "2-9°C", condition: "Cold", description: "Still chilly, similar to January" },
    March: { temp: "5-13°C", condition: "Cool", description: "Spring starting, variable weather" },
    April: { temp: "9-17°C", condition: "Pleasant", description: "Spring flowers blooming, mild weather" },
    May: { temp: "13-21°C", condition: "Warm", description: "Beautiful weather for sightseeing" },
    June: { temp: "17-25°C", condition: "Sunny", description: "Early summer, perfect for travel" },
    July: { temp: "20-28°C", condition: "Sunny", description: "Peak summer season, very warm" },
    August: { temp: "19-27°C", condition: "Warm", description: "Still hot, many French people on vacation" },
    September: { temp: "15-22°C", condition: "Pleasant", description: "Fall arrives, still warm and pleasant" },
    October: { temp: "10-16°C", condition: "Cool", description: "Fall colors, cooler temperatures" },
    November: { temp: "6-11°C", condition: "Cold", description: "Getting colder, more rain" },
    December: { temp: "3-8°C", condition: "Cold", description: "Winter, occasional frost" },
  },
  "Japan": {
    January: { temp: "3-10°C", condition: "Cold & Dry", description: "Winter season, clear skies" },
    February: { temp: "3-11°C", condition: "Cold", description: "Still cold but starting to warm" },
    March: { temp: "7-17°C", condition: "Cool", description: "Cherry blossom season approaching" },
    April: { temp: "13-23°C", condition: "Mild & Sunny", description: "Cherry blossoms in full bloom" },
    May: { temp: "18-27°C", condition: "Warm", description: "Golden week holidays, pleasant weather" },
    June: { temp: "21-28°C", condition: "Hot & Humid", description: "Rainy season (tsuyu) begins" },
    July: { temp: "25-32°C", condition: "Very Hot & Humid", description: "Peak summer heat and humidity" },
    August: { temp: "26-33°C", condition: "Hot & Humid", description: "Still very hot, typhoon season risk" },
    September: { temp: "20-27°C", condition: "Warm & Humid", description: "Typhoon season, cooling down" },
    October: { temp: "14-22°C", condition: "Pleasant", description: "Fall foliage, comfortable weather" },
    November: { temp: "9-17°C", condition: "Cool", description: "Autumn colors peak, getting chilly" },
    December: { temp: "4-11°C", condition: "Cold", description: "Winter approaches, clear days" },
  },
  "Thailand": {
    January: { temp: "24-32°C", condition: "Sunny & Dry", description: "Best weather for travel" },
    February: { temp: "25-33°C", condition: "Sunny & Hot", description: "Perfect beach weather" },
    March: { temp: "27-35°C", condition: "Very Hot", description: "Peak summer heat begins" },
    April: { temp: "28-36°C", condition: "Hot & Humid", description: "Hottest month, Songkran festival" },
    May: { temp: "25-33°C", condition: "Hot & Rainy", description: "Rainy season starts" },
    June: { temp: "24-31°C", condition: "Rainy", description: "Southwest monsoon, frequent rain" },
    July: { temp: "24-30°C", condition: "Rainy & Hot", description: "Heavy rain, high humidity" },
    August: { temp: "23-30°C", condition: "Rainy", description: "Rainy season continues" },
    September: { temp: "23-30°C", condition: "Rainy", description: "Heaviest rain month" },
    October: { temp: "23-31°C", condition: "Rainy & Warm", description: "Rain decreasing towards end" },
    November: { temp: "22-31°C", condition: "Dry & Sunny", description: "Start of cool season" },
    December: { temp: "21-30°C", condition: "Sunny & Dry", description: "Best season, comfortable heat" },
  },
  "Spain": {
    January: { temp: "5-14°C", condition: "Cool", description: "Winter, occasional rain" },
    February: { temp: "6-15°C", condition: "Cool", description: "Still cold but improving" },
    March: { temp: "8-18°C", condition: "Mild", description: "Spring beginning" },
    April: { temp: "11-21°C", condition: "Pleasant", description: "Nice spring weather" },
    May: { temp: "15-26°C", condition: "Warm", description: "Perfect for outdoor activities" },
    June: { temp: "20-31°C", condition: "Hot & Sunny", description: "Summer season, very warm" },
    July: { temp: "23-34°C", condition: "Very Hot & Sunny", description: "Peak heat, peak season" },
    August: { temp: "22-33°C", condition: "Hot", description: "Still very hot, many on vacation" },
    September: { temp: "18-29°C", condition: "Warm", description: "Cooling down, still pleasant" },
    October: { temp: "13-22°C", condition: "Pleasant", description: "Fall weather, comfortable" },
    November: { temp: "8-16°C", condition: "Cool", description: "Getting colder, some rain" },
    December: { temp: "5-12°C", condition: "Cold", description: "Winter arrives" },
  },
  "Italy": {
    January: { temp: "3-12°C", condition: "Cold", description: "Winter season" },
    February: { temp: "4-13°C", condition: "Cold", description: "Still cold but improving" },
    March: { temp: "7-17°C", condition: "Cool", description: "Spring approaching" },
    April: { temp: "12-22°C", condition: "Pleasant", description: "Perfect spring weather" },
    May: { temp: "17-27°C", condition: "Warm & Sunny", description: "Beautiful weather for travel" },
    June: { temp: "21-31°C", condition: "Hot & Sunny", description: "Summer begins" },
    July: { temp: "24-33°C", condition: "Very Hot", description: "Peak summer heat" },
    August: { temp: "23-32°C", condition: "Hot", description: "Still very warm" },
    September: { temp: "19-28°C", condition: "Warm", description: "Late summer, cooling slightly" },
    October: { temp: "13-22°C", condition: "Pleasant", description: "Fall weather, comfortable" },
    November: { temp: "8-16°C", condition: "Cool", description: "Getting cooler" },
    December: { temp: "4-12°C", condition: "Cold", description: "Winter weather" },
  },
  "Australia": {
    January: { temp: "25-35°C", condition: "Hot & Humid", description: "Peak summer heat" },
    February: { temp: "24-34°C", condition: "Hot", description: "Still very hot" },
    March: { temp: "21-31°C", condition: "Warm", description: "Autumn beginning" },
    April: { temp: "17-27°C", condition: "Pleasant", description: "Cool autumn weather" },
    May: { temp: "13-22°C", condition: "Cool", description: "Autumn in full swing" },
    June: { temp: "10-18°C", condition: "Cold", description: "Winter beginning" },
    July: { temp: "9-17°C", condition: "Cold", description: "Coldest month" },
    August: { temp: "11-19°C", condition: "Cool", description: "Starting to warm up" },
    September: { temp: "14-24°C", condition: "Pleasant", description: "Spring beginning" },
    October: { temp: "19-29°C", condition: "Warm & Sunny", description: "Spring in full swing" },
    November: { temp: "22-32°C", condition: "Warm", description: "Summer approaching" },
    December: { temp: "24-34°C", condition: "Hot", description: "Summer begins" },
  },
  "Greece": {
    January: { temp: "6-13°C", condition: "Cool", description: "Winter on the islands" },
    February: { temp: "7-14°C", condition: "Cool", description: "Still chilly" },
    March: { temp: "9-17°C", condition: "Mild", description: "Spring approaching" },
    April: { temp: "15-24°C", condition: "Pleasant", description: "Easter weather improving" },
    May: { temp: "20-29°C", condition: "Warm & Sunny", description: "Perfect beach weather" },
    June: { temp: "25-33°C", condition: "Hot & Sunny", description: "Summer season" },
    July: { temp: "28-35°C", condition: "Very Hot & Sunny", description: "Peak summer" },
    August: { temp: "27-35°C", condition: "Hot", description: "Very hot, peak tourism" },
    September: { temp: "23-31°C", condition: "Warm", description: "Late summer" },
    October: { temp: "17-26°C", condition: "Pleasant", description: "Fall weather" },
    November: { temp: "11-20°C", condition: "Cool", description: "Getting cooler" },
    December: { temp: "7-14°C", condition: "Cool", description: "Winter season" },
  },
  "Brazil": {
    January: { temp: "25-34°C", condition: "Hot & Humid", description: "Summer season" },
    February: { temp: "25-34°C", condition: "Hot & Humid", description: "Carnival season" },
    March: { temp: "24-32°C", condition: "Warm & Humid", description: "Cooling slightly" },
    April: { temp: "22-30°C", condition: "Warm", description: "Fall beginning" },
    May: { temp: "19-27°C", condition: "Pleasant", description: "Comfortable temperatures" },
    June: { temp: "17-25°C", condition: "Cool", description: "Winter beginning" },
    July: { temp: "16-24°C", condition: "Cool", description: "Coldest month" },
    August: { temp: "17-26°C", condition: "Cool & Dry", description: "Dry season" },
    September: { temp: "20-28°C", condition: "Warm & Dry", description: "Spring beginning" },
    October: { temp: "23-31°C", condition: "Warm", description: "Heating up" },
    November: { temp: "24-32°C", condition: "Hot & Humid", description: "Summer approaching" },
    December: { temp: "25-33°C", condition: "Hot & Humid", description: "Summer begins" },
  },
  "Canada": {
    January: { temp: "-10 to -2°C", condition: "Very Cold", description: "Deep winter, snow common" },
    February: { temp: "-10 to -1°C", condition: "Very Cold", description: "Still very cold" },
    March: { temp: "-5 to 4°C", condition: "Cold", description: "Spring snow still possible" },
    April: { temp: "2 to 12°C", condition: "Cool", description: "Spring thaw beginning" },
    May: { temp: "10 to 20°C", condition: "Pleasant", description: "Spring in full swing" },
    June: { temp: "16 to 25°C", condition: "Warm", description: "Beautiful early summer" },
    July: { temp: "19 to 27°C", condition: "Warm & Sunny", description: "Peak summer" },
    August: { temp: "18 to 26°C", condition: "Warm", description: "Still pleasant" },
    September: { temp: "13 to 20°C", condition: "Cool", description: "Fall colors starting" },
    October: { temp: "7 to 14°C", condition: "Cool", description: "Fall in full swing" },
    November: { temp: "1 to 7°C", condition: "Cold", description: "Getting ready for winter" },
    December: { temp: "-7 to -1°C", condition: "Very Cold", description: "Winter returns" },
  },
  "Mexico": {
    January: { temp: "20-27°C", condition: "Warm & Dry", description: "Dry season begins" },
    February: { temp: "21-28°C", condition: "Warm & Dry", description: "Perfect beach weather" },
    March: { temp: "23-30°C", condition: "Hot & Dry", description: "Getting warmer" },
    April: { temp: "25-32°C", condition: "Hot", description: "Very warm, before rains" },
    May: { temp: "25-33°C", condition: "Hot & Humid", description: "Rainy season approaching" },
    June: { temp: "24-31°C", condition: "Hot & Rainy", description: "Rainy season begins" },
    July: { temp: "23-30°C", condition: "Warm & Rainy", description: "Heavy rain possible" },
    August: { temp: "23-30°C", condition: "Warm & Rainy", description: "Rainy season continues" },
    September: { temp: "23-29°C", condition: "Warm & Rainy", description: "Hurricane season" },
    October: { temp: "22-30°C", condition: "Warm & Rainy", description: "Rains decreasing" },
    November: { temp: "20-28°C", condition: "Warm & Dry", description: "Dry season returning" },
    December: { temp: "19-26°C", condition: "Warm & Dry", description: "Perfect weather" },
  },
};
// Merge additional country entries into the primary database (no duplicates — first wins)
Object.assign(_climateDatabase2, climateDatabase);
Object.assign(climateDatabase, _climateDatabase2);

/**
 * Get climate estimate for a country and month
 */
export function getClimateEstimate(
  country: string,
  month: string
): ClimateData {
  const countryData = climateDatabase[country];

  if (!countryData) {
    // Default fallback if country not found
    return {
      temp: "15-25°C",
      condition: "Comfortable",
      icon: "🌍",
      description: "Typical pleasant weather for the season",
    };
  }

  const monthData = countryData[month];

  if (!monthData) {
    // Default fallback if month not found
    return {
      temp: "15-25°C",
      condition: "Comfortable",
      icon: "🌍",
      description: "Typical weather",
    };
  }

  return monthData;
}
